---
- name: Install package
  become: True
  package:
    name: kubernetes-hyperkube-kube-controller-manager
    state: present
    update_cache: True

- name: Configure package
  become: True
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart kube-controller-manager

- name: Flush handlers
  meta: flush_handlers

