---
- name: Reload systemd
  become: True
  systemd:
    daemon_reload: True

- name: Restart kube-controller-manager
  become: True
  service:
    name: kube-controller-manager
    state: restarted
    enabled: True
